### ISSUE TITLE
There was an error parsing the logs. More info: «no additional info»

### ISSUE THREAD

**Issue by TexasCoyote** [bananahampster/hampalyzer#24]
Attempting to process the log files from the most recent OST pickup night failed with the error: There was an error parsing the logs. More info: «no additional info

Log files:
[OST-Pickup-2022-01-02-Rd1-Troy2.log](https://github.com/bananahampster/hampalyzer/files/7803639/OST-Pickup-2022-01-02-Rd1-Troy2.log)
[OST-Pickup-2022-01-02-Rd2-Palermo.log](https://github.com/bananahampster/hampalyzer/files/7803640/OST-Pickup-2022-01-02-Rd2-Palermo.log)
[OST-Pickup-2022-01-02-Rd3-cmhf.log](https://github.com/bananahampster/hampalyzer/files/7803641/OST-Pickup-2022-01-02-Rd3-cmhf.log)
[OST-Pickup-2022-01-02-Rd4-Rasen.log](https://github.com/bananahampster/hampalyzer/files/7803642/OST-Pickup-2022-01-02-Rd4-Rasen.log)
[OST-Pickup-2022-01-02-Rd5-Rasen.log](https://github.com/bananahampster/hampalyzer/files/7803643/OST-Pickup-2022-01-02-Rd5-Rasen.log)
»

**Comment by bananahampster** [comment]
Fixed by
