### ISSUE TITLE
Broken logs on siden

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#25]
I don't think this is reproducible since I'm not sure what happened, but this log came out all garbled: http://app.hampalyzer.com/parsedlogs/Coach's-2022-Mar-16-23-17/

The equivalent blarghs seem to be fine:
http://blarghalyzer.com/parsedlogs/coach-l0316055/
http://blarghalyzer.com/parsedlogs/coach-l0316056/

Raw logs:
[L0316053.log](https://github.com/bananahampster/hampalyzer/files/8276760/L0316053.log)
[L0316054.log](https://github.com/bananahampster/hampalyzer/files/8276761/L0316054.log)

**Comment by LightTreason** [comment]
The Blarghalyzer blogs are from different logs (they end in 55 and 56). The logs you uploaded appear to be for a different pre-game map (e.g. there's green team players) and the 54 log is a log that lasted less than two minutes before the server was restarted.

**Comment by Nomad7** [comment]
Very sorry for the hassle, I did something similarly dumb with #29 too :(
Will try to be more diligent in the future!
