### ISSUE TITLE
403 for destroy_l logs

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#31]
[apr14h2v2destroyr1.log](https://github.com/bananahampster/hampalyzer/files/8491575/apr14h2v2destroyr1.log)
[apr14h2v2destroyr2.log](https://github.com/bananahampster/hampalyzer/files/8491576/apr14h2v2destroyr2.log)
403 here http://app.hampalyzer.com/parsedlogs/Unknown-2022-Apr-14-13-42/

but blarghalizes just fine:
http://www.blarghalyzer.com/parsedlogs/l0414058/
http://www.blarghalyzer.com/parsedlogs/l0414060/

**Comment by LightTreason** [comment]
This map had non-standard team names ("Blue :D?" and "Red :D?"). I updated the general parsing logic to preserve entire strings that were quoted, upgraded the rest of the code to understand that, and then added a one-off mapping for these names.

**Comment by LightTreason** [comment]
See http://app.hampalyzer.com/parsedlogs/Unknown-2022-Apr-14-13-42-knxfo/ for these logs being successfully parsed.
