### ISSUE TITLE
haste_r logs broken

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#32]
It looks like there may be multiple issues with this - with the following line in place:
L 05/03/2022 - 12:44:31: "hello? Nomad [BOISY] pls<5><STEAM_0:1:5107><Blue>" committed suicide with "door_rotating" (world)
the result is "There was an error parsing the logs. More info: «no additional info»"

If I manually change that suicide from "door_rotating" to "worldspawn" instead, the result is a 403 error: http://app.hampalyzer.com/parsedlogs/Unknown-2022-May-3-12-36-t46aa/

[hellopickupmay3haster1b.log](https://github.com/bananahampster/hampalyzer/files/8612743/hellopickupmay3haster1b.log)
[hellopickupmay3haster2b.log](https://github.com/bananahampster/hampalyzer/files/8612744/hellopickupmay3haster2b.log)

**Comment by LightTreason** [comment]
Fixed in 5f23b3de514716f6fa1fb56cff7083ec475afe6e.

See http://app.hampalyzer.com/parsedlogs/Unknown-2022-May-3-12-46/.
