### ISSUE TITLE
Congestus logs broken

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#34]
[L0612005.log](https://github.com/bananahampster/hampalyzer/files/8885219/L0612005.log)
[L0612006.log](https://github.com/bananahampster/hampalyzer/files/8885220/L0612006.log)

Attempting to submit these logs results in an error: 
> There was an error parsing the logs. More info: «no additional info»

Hamp sent me the error (healing a tranq effect) before I finished submitting this ticket but I'll post it here for the record:

> Failed to parse line number 3791: "Features-<4><STEAM_0:0:92298><Blue>" triggered "Medic_Cured_Tranquilisation" against "Doug<8><STEAM_0:1:5622><Blue>"

(removing this line allowed the logs to be uploaded and parsed successfully)

**Comment by bananahampster** [comment]
will be resolved by `8b16caa1` (in the hamp/reparse branch)
