### ISSUE TITLE
Classes played is not always accurate

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#5]
I haven't seen any particular pattern yet, but sometimes (randomly?) the classes played are incorrect. This is most commonly noticed when someone plays scout and medic, but only scout is shown. Here's an example: http://app.hampalyzer.com/parsedlogs/Coach's-2021-Jul-15-15-01/ (I did not get 22 kills as scout :))

Logs courtesy of coachsouz:
R1: https://pastebin.com/nAGbSBM3
R2 (in case it's relevant): https://pastebin.com/vB7jdGKB

**Comment by Nomad7** [comment]
Another example, Wheaties switched to soldier for the last 10 seconds of round 2 but it only shows soldier, not heavy: http://app.hampalyzer.com/parsedlogs/Coach's-2021-Jul-15-17-14/

**Comment by bananahampster** [comment]
Fixed via a0e3099
