### ISSUE TITLE
Some logs result in: There was an error parsing the logs. More info: «no additional info»

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#8]
Sorry this is super vague, but sometimes, some logs can't be parsed. Doesn't seem to be a pattern based on server, map, or any other obvious thing that jumped out at me, but occasionally logs will give this error instead of parsing.
Attached are some logs that errored for me.
[schtopr1.log](https://github.com/bananahampster/hampalyzer/files/7063968/schtopr1.log)
[schtopr2.log](https://github.com/bananahampster/hampalyzer/files/7063969/schtopr2.log)

**Comment by Nomad7** [comment]
Here's another example on baconbowl_r, these logs for the error message described in the topic:
[hellotnsbaconbowlr1.log](https://github.com/bananahampster/hampalyzer/files/7448607/hellotnsbaconbowlr1.log)
[hellotnsbaconbowlr2.log](https://github.com/bananahampster/hampalyzer/files/7448608/hellotnsbaconbowlr2.log)

In this case the equivalent blargs appear to be working just fine (unless I missed something):
http://blarghalyzer.com/parsedlogs/hellotnsbaconbowlr1/
http://blarghalyzer.com/parsedlogs/hellotnsbaconbowlr2/

If there's anything more useful I can do to help troubleshoot this (or just find more broken logs) let me know :)

**Comment by Nomad7** [comment]
Another example: hello vs thx on torch2, blarghs seem to be fine but hampalyzer errors
[hellothxtorch2r1.log](https://github.com/bananahampster/hampalyzer/files/7742483/hellothxtorch2r1.log)
[hellothxtorch2r2.log](https://github.com/bananahampster/hampalyzer/files/7742484/hellothxtorch2r2.log)
vs
http://blarghalyzer.com/parsedlogs/hellothxtorch2r1/
http://blarghalyzer.com/parsedlogs/hellothxtorch2r2/

**Comment by bananahampster** [comment]
Here's what I've found so far:
* those schtop logs: you've truncated necessary events like "player joined team", so hampalyzer doesn't know which team to assign to each players.  This is expected behavior.
* stormz2: "env_beam world" are the flag lasers' weapon name, added
* baconbowl: 
    * "#dustbowl_team1" and "#dustbowl_team2" are the names of the teams (those are customizable per-map???)
    * "rock_laser_kill world" is the name of the gate lasers' weapon
* torch2: kacchan cured klumy's hallucinations: `triggered "Medic_Cured_Hallucinations"`
